#ifndef BB_SCPCB_COMMANDS_H
#define BB_SCPCB_COMMANDS_H

#include <bb/blitz/module.h>
#include <bb/scpcb/scpcb.h>

#ifdef __cplusplus
extern "C" {
#endif

// AUTOGENERATED. DO NOT EDIT.
// RUN `make` TO UPDATE.

// FMOD 3 (streams only-- sound effects go through the Blitz audio commands)
bb_int_t BBCALL bbFSOUND_Init( bb_int_t freq,bb_int_t channels,bb_int_t flags );
bb_int_t BBCALL bbFSOUND_Close(  );
void BBCALL bbFSOUND_SetVolume( bb_int_t channel,bb_int_t vol );
bb_int_t BBCALL bbFSOUND_SetVolumeAbsolute( bb_int_t channel,bb_int_t vol );
bb_int_t BBCALL bbFSOUND_GetVolume( bb_int_t channel );
void BBCALL bbFSOUND_SetPaused( bb_int_t channel,bb_int_t paused );
void BBCALL bbFSOUND_StopSound( bb_int_t channel );
bb_int_t BBCALL bbFSOUND_Stream_Play( bb_int_t channel,bb_int_t stream );
bb_int_t BBCALL bbFSOUND_Stream_Stop( bb_int_t stream );
bb_int_t BBCALL bbFSOUND_Stream_Close( bb_int_t stream );
bb_int_t BBCALL bbFSOUND_Stream_Open( BBStr *filename,bb_int_t mode,bb_int_t memlength );
bb_int_t BBCALL bbFSOUND_IsPlaying( bb_int_t channel );
bb_int_t BBCALL bbFSOUND_SetPan( bb_int_t channel,bb_int_t pan );

// debug aid (not part of the original game)
void BBCALL bbRT_Trace( BBStr *msg );

// cpuid.dll
BBStr * BBCALL bbCPUid(  );
BBStr * BBCALL bbCPUextendedId(  );
BBStr * BBCALL bbCPUbrand(  );
BBStr * BBCALL bbCPUfeatures(  );
bb_int_t BBCALL bbCPUmodel(  );
bb_int_t BBCALL bbCPUfamily(  );
bb_int_t BBCALL bbCPUsteppingId(  );
bb_int_t BBCALL bbCPUl1cache(  );
bb_int_t BBCALL bbCPUl2cache(  );

// BlitzMovie.dll (the startup video is not played)
bb_int_t BBCALL bbBlitzMovie_Open( BBStr *name );
void BBCALL bbBlitzMovie_Close(  );
bb_int_t BBCALL bbBlitzMovie_GetWidth(  );
bb_int_t BBCALL bbBlitzMovie_GetHeight(  );
bb_int_t BBCALL bbBlitzMovie_GetPixel( bb_int_t offset );
bb_int_t BBCALL bbBlitzMovie_Play(  );
bb_int_t BBCALL bbBlitzMovie_Stop(  );
bb_int_t BBCALL bbBlitzMovie_OpenD3D( BBStr *name,bb_int_t device,bb_int_t ddraw );
bb_int_t BBCALL bbBlitzMovie_DrawD3D( bb_int_t x,bb_int_t y,bb_int_t width,bb_int_t height );
bb_int_t BBCALL bbBlitzMovie_MuteAudio(  );
bb_int_t BBCALL bbBlitzMovie_SetVolume( bb_int_t volume );
bb_int_t BBCALL bbBlitzMovie_IsPlaying(  );
bb_int_t BBCALL bbBlitzMovie_OpenDecodeToImage( BBStr *name,bb_int_t buffer,bb_int_t looping );
bb_int_t BBCALL bbBlitzMovie_OpenDecodeToTexture( BBStr *name,bb_int_t buffer,bb_int_t looping );
bb_int_t BBCALL bbBlitzMovie_Pause(  );

// user32 / kernel32 (windowing is owned by the runtime)
bb_int_t BBCALL bbapi_GetClientRect( bb_int_t hwnd,bb_int_t rect );
bb_int_t BBCALL bbapi_GetDesktopWindow(  );
bb_int_t BBCALL bbapi_GetFocus(  );
bb_int_t BBCALL bbapi_SetWindowLong( bb_int_t hwnd,bb_int_t index,bb_int_t value );
bb_int_t BBCALL bbapi_SetWindowPos( bb_int_t hwnd,bb_int_t after,bb_int_t x,bb_int_t y,bb_int_t cx,bb_int_t cy,bb_int_t flags );
bb_int_t BBCALL bbapi_GetModuleFileName( bb_int_t module,BBStr *filename,bb_int_t size );
void BBCALL bbapi_GlobalMemoryStatus( void *buffer );
void BBCALL bbGlobalMemoryStatus( void *buffer );

// zlibwapi.dll (only the self-updater uses it, and there is no updater here)
BBStr * BBCALL bbZlibWapi_zError( bb_int_t code );
BBStr * BBCALL bbZlibWapi_ZlibVersion(  );
bb_int_t BBCALL bbZlibWapi_CompressBound( bb_int_t length );
bb_int_t BBCALL bbZlibWapi_Compress( bb_int_t dest,bb_int_t destsize,bb_int_t source,bb_int_t sourcesize );
bb_int_t BBCALL bbZlibWapi_Compress2( bb_int_t dest,bb_int_t destsize,bb_int_t source,bb_int_t sourcesize,bb_int_t level );
bb_int_t BBCALL bbZlibWapi_UnCompress( bb_int_t dest,bb_int_t destsize,bb_int_t source,bb_int_t sourcesize );
bb_int_t BBCALL bbZlibWapi_Adler32( bb_int_t adler,bb_int_t buffer,bb_int_t length );
bb_int_t BBCALL bbZlibWapi_Crc32( bb_int_t crc,bb_int_t buffer,bb_int_t length );
bb_int_t BBCALL bbZlibWapi_UnzOpen( BBStr *path );
bb_int_t BBCALL bbZlibWapi_UnzClose( bb_int_t zip );
bb_int_t BBCALL bbZlibWapi_UnzGetGlobalInfo( bb_int_t zip,bb_int_t info );
bb_int_t BBCALL bbZlibWapi_UnzGetGlobalComment( bb_int_t zip,bb_int_t comment,bb_int_t length );
bb_int_t BBCALL bbZlibWapi_UnzLocateFile( bb_int_t zip,BBStr *name,bb_int_t casesensitive );
bb_int_t BBCALL bbZlibWapi_UnzGoToFirstFile( bb_int_t zip );
bb_int_t BBCALL bbZlibWapi_UnzGoToNextFile( bb_int_t zip );
bb_int_t BBCALL bbZlibWapi_UnzGetCurrentFileInfo( bb_int_t zip,bb_int_t info,bb_int_t name,bb_int_t namesize,bb_int_t extra,bb_int_t extrasize,bb_int_t comment,bb_int_t commentsize );
bb_int_t BBCALL bbZlibWapi_UnzOpenCurrentFile( bb_int_t zip );
bb_int_t BBCALL bbZlibWapi_UnzOpenCurrentFilePassword( bb_int_t zip,BBStr *password );
bb_int_t BBCALL bbZlibWapi_UnzReadCurrentFile( bb_int_t zip,bb_int_t buffer,bb_int_t length );
bb_int_t BBCALL bbZlibWapi_UnzCloseCurrentFile( bb_int_t zip );
bb_int_t BBCALL bbZlibWapi_ZipOpen( BBStr *name,bb_int_t append );
bb_int_t BBCALL bbZlibWapi_ZipClose( bb_int_t zip,BBStr *comment );
bb_int_t BBCALL bbZlibWapi_ZipOpenNewFileInZip( bb_int_t zip,BBStr *name,bb_int_t info,bb_int_t localextra,bb_int_t localextrasize,bb_int_t globalextra,bb_int_t globalextrasize,BBStr *comment,bb_int_t method,bb_int_t level );
bb_int_t BBCALL bbZlibWapi_ZipOpenNewFileInZip3( bb_int_t zip,BBStr *name,bb_int_t info,bb_int_t localextra,bb_int_t localextrasize,bb_int_t globalextra,bb_int_t globalextrasize,BBStr *comment,bb_int_t method,bb_int_t level,bb_int_t raw,bb_int_t windowbits,bb_int_t memlevel,bb_int_t strategy,BBStr *password,bb_int_t crc );
bb_int_t BBCALL bbZlibWapi_ZipWriteFileInZip( bb_int_t zip,bb_int_t data,bb_int_t length );
bb_int_t BBCALL bbZlibWapi_ZipCloseFileInZip( bb_int_t zip );

#ifdef __cplusplus
}
#endif


#endif
