#ifndef BB_SCPCB_COMMANDS_H
#define BB_SCPCB_COMMANDS_H

#include <bb/blitz/module.h>
#include <bb/scpcb/scpcb.h>

#ifdef __cplusplus
extern "C" {
#endif

// AUTOGENERATED. DO NOT EDIT.
// RUN `make` TO UPDATE.

// FMOD 3 (streams only-- sound effects go through the Blitz audio commands)
bb_int_t BBCALL bbFSOUND_Init( bb_int_t freq,bb_int_t channels,bb_int_t flags );
bb_int_t BBCALL bbFSOUND_Close(  );
void BBCALL bbFSOUND_SetVolume( bb_int_t channel,bb_int_t vol );
bb_int_t BBCALL bbFSOUND_SetVolumeAbsolute( bb_int_t channel,bb_int_t vol );
bb_int_t BBCALL bbFSOUND_GetVolume( bb_int_t channel );
void BBCALL bbFSOUND_SetPaused( bb_int_t channel,bb_int_t paused );
void BBCALL bbFSOUND_StopSound( bb_int_t channel );
bb_int_t BBCALL bbFSOUND_Stream_Play( bb_int_t channel,bb_int_t stream );
bb_int_t BBCALL bbFSOUND_Stream_Stop( bb_int_t stream );
bb_int_t BBCALL bbFSOUND_Stream_Close( bb_int_t stream );
bb_int_t BBCALL bbFSOUND_Stream_Open( BBStr *filename,bb_int_t mode,bb_int_t memlength );
bb_int_t BBCALL bbFSOUND_IsPlaying( bb_int_t channel );
bb_int_t BBCALL bbFSOUND_SetPan( bb_int_t channel,bb_int_t pan );

// debug aid (not part of the original game)
void BBCALL bbRT_Trace( BBStr *msg );

// on-screen keyboard (Switch)-- RT_HasPrompt% is 0 where a real keyboard exists
bb_int_t BBCALL bbRT_HasPrompt(  );
BBStr * BBCALL bbRT_TextPrompt( BBStr *title,BBStr *initial );

// port settings (switch_settings.ini, edited by the overlay menu)
bb_float_t BBCALL bbRT_SettingF( BBStr *key,bb_float_t def );
bb_int_t BBCALL bbRT_SettingI( BBStr *key,bb_int_t def );
BBStr * BBCALL bbRT_SettingS( BBStr *key,BBStr *def );

// gamepad inventory navigation: the game reports the slot centres every frame an inventory is open
void BBCALL bbRT_PadInvBegin(  );
void BBCALL bbRT_PadInvSlot( bb_int_t x,bb_int_t y );
void BBCALL bbRT_PadMenuBegin(  );
void BBCALL bbRT_PadMenuRect( bb_int_t x,bb_int_t y,bb_int_t w,bb_int_t h );

// cpuid.dll
BBStr * BBCALL bbCPUid(  );
BBStr * BBCALL bbCPUextendedId(  );
BBStr * BBCALL bbCPUbrand(  );
BBStr * BBCALL bbCPUfeatures(  );
bb_int_t BBCALL bbCPUmodel(  );
bb_int_t BBCALL bbCPUfamily(  );
bb_int_t BBCALL bbCPUsteppingId(  );
bb_int_t BBCALL bbCPUl1cache(  );
bb_int_t BBCALL bbCPUl2cache(  );

// BlitzMovie.dll (the startup video is not played)
bb_int_t BBCALL bbBlitzMovie_Open( BBStr *name );
void BBCALL bbBlitzMovie_Close(  );
bb_int_t BBCALL bbBlitzMovie_GetWidth(  );
bb_int_t BBCALL bbBlitzMovie_GetHeight(  );
bb_int_t BBCALL bbBlitzMovie_GetPixel( bb_int_t offset );
bb_int_t BBCALL bbBlitzMovie_Play(  );
bb_int_t BBCALL bbBlitzMovie_Stop(  );
bb_int_t BBCALL bbBlitzMovie_OpenD3D( BBStr *name,bb_int_t device,bb_int_t ddraw );
bb_int_t BBCALL bbBlitzMovie_DrawD3D( bb_int_t x,bb_int_t y,bb_int_t width,bb_int_t height );
bb_int_t BBCALL bbBlitzMovie_MuteAudio(  );
bb_int_t BBCALL bbBlitzMovie_SetVolume( bb_int_t volume );
bb_int_t BBCALL bbBlitzMovie_IsPlaying(  );
bb_int_t BBCALL bbBlitzMovie_OpenDecodeToImage( BBStr *name,bb_int_t buffer,bb_int_t looping );
bb_int_t BBCALL bbBlitzMovie_OpenDecodeToTexture( BBStr *name,bb_int_t buffer,bb_int_t looping );
bb_int_t BBCALL bbBlitzMovie_Pause(  );

// user32 / kernel32 (windowing is owned by the runtime)
bb_int_t BBCALL bbapi_GetClientRect( bb_int_t hwnd,bb_int_t rect );
bb_int_t BBCALL bbapi_GetDesktopWindow(  );
bb_int_t BBCALL bbapi_GetFocus(  );
bb_int_t BBCALL bbapi_SetWindowLong( bb_int_t hwnd,bb_int_t index,bb_int_t value );
bb_int_t BBCALL bbapi_SetWindowPos( bb_int_t hwnd,bb_int_t after,bb_int_t x,bb_int_t y,bb_int_t cx,bb_int_t cy,bb_int_t flags );
bb_int_t BBCALL bbapi_GetModuleFileName( bb_int_t module,BBStr *filename,bb_int_t size );
void BBCALL bbapi_GlobalMemoryStatus( void *buffer );
void BBCALL bbGlobalMemoryStatus( void *buffer );

// zlibwapi.dll (only the self-updater uses it, and there is no updater here)
BBStr * BBCALL bbZlibWapi_zError( bb_int_t code );
BBStr * BBCALL bbZlibWapi_ZlibVersion(  );
bb_int_t BBCALL bbZlibWapi_CompressBound( bb_int_t length );
bb_int_t BBCALL bbZlibWapi_Compress( bb_int_t dest,bb_int_t destsize,bb_int_t source,bb_int_t sourcesize );
bb_int_t BBCALL bbZlibWapi_Compress2( bb_int_t dest,bb_int_t destsize,bb_int_t source,bb_int_t sourcesize,bb_int_t level );
bb_int_t BBCALL bbZlibWapi_UnCompress( bb_int_t dest,bb_int_t destsize,bb_int_t source,bb_int_t sourcesize );
bb_int_t BBCALL bbZlibWapi_Adler32( bb_int_t adler,bb_int_t buffer,bb_int_t length );
bb_int_t BBCALL bbZlibWapi_Crc32( bb_int_t crc,bb_int_t buffer,bb_int_t length );
bb_int_t BBCALL bbZlibWapi_UnzOpen( BBStr *path );
bb_int_t BBCALL bbZlibWapi_UnzClose( bb_int_t zip );
bb_int_t BBCALL bbZlibWapi_UnzGetGlobalInfo( bb_int_t zip,bb_int_t info );
bb_int_t BBCALL bbZlibWapi_UnzGetGlobalComment( bb_int_t zip,bb_int_t comment,bb_int_t length );
bb_int_t BBCALL bbZlibWapi_UnzLocateFile( bb_int_t zip,BBStr *name,bb_int_t casesensitive );
bb_int_t BBCALL bbZlibWapi_UnzGoToFirstFile( bb_int_t zip );
bb_int_t BBCALL bbZlibWapi_UnzGoToNextFile( bb_int_t zip );
bb_int_t BBCALL bbZlibWapi_UnzGetCurrentFileInfo( bb_int_t zip,bb_int_t info,bb_int_t name,bb_int_t namesize,bb_int_t extra,bb_int_t extrasize,bb_int_t comment,bb_int_t commentsize );
bb_int_t BBCALL bbZlibWapi_UnzOpenCurrentFile( bb_int_t zip );
bb_int_t BBCALL bbZlibWapi_UnzOpenCurrentFilePassword( bb_int_t zip,BBStr *password );
bb_int_t BBCALL bbZlibWapi_UnzReadCurrentFile( bb_int_t zip,bb_int_t buffer,bb_int_t length );
bb_int_t BBCALL bbZlibWapi_UnzCloseCurrentFile( bb_int_t zip );
bb_int_t BBCALL bbZlibWapi_ZipOpen( BBStr *name,bb_int_t append );
bb_int_t BBCALL bbZlibWapi_ZipClose( bb_int_t zip,BBStr *comment );
bb_int_t BBCALL bbZlibWapi_ZipOpenNewFileInZip( bb_int_t zip,BBStr *name,bb_int_t info,bb_int_t localextra,bb_int_t localextrasize,bb_int_t globalextra,bb_int_t globalextrasize,BBStr *comment,bb_int_t method,bb_int_t level );
bb_int_t BBCALL bbZlibWapi_ZipOpenNewFileInZip3( bb_int_t zip,BBStr *name,bb_int_t info,bb_int_t localextra,bb_int_t localextrasize,bb_int_t globalextra,bb_int_t globalextrasize,BBStr *comment,bb_int_t method,bb_int_t level,bb_int_t raw,bb_int_t windowbits,bb_int_t memlevel,bb_int_t strategy,BBStr *password,bb_int_t crc );
bb_int_t BBCALL bbZlibWapi_ZipWriteFileInZip( bb_int_t zip,bb_int_t data,bb_int_t length );
bb_int_t BBCALL bbZlibWapi_ZipCloseFileInZip( bb_int_t zip );

// UE Reborn: IniController (BlitzToolbox)
void BBCALL bbIniClearBuffer( BBStr *path );
void BBCALL bbIniWriteBuffer_( BBStr *path,bb_int_t clear );
BBStr * BBCALL bbIniGetString_( BBStr *path,BBStr *section,BBStr *key,BBStr *def,bb_int_t allow );
bb_int_t BBCALL bbIniGetInt_( BBStr *path,BBStr *section,BBStr *key,bb_int_t def,bb_int_t allow );
bb_float_t BBCALL bbIniGetFloat_( BBStr *path,BBStr *section,BBStr *key,bb_float_t def,bb_int_t allow );
BBStr * BBCALL bbIniGetBufferString_( BBStr *path,BBStr *section,BBStr *key,BBStr *def );
void BBCALL bbIniWriteString_( BBStr *path,BBStr *section,BBStr *key,BBStr *value,bb_int_t update );
void BBCALL bbIniWriteInt_( BBStr *path,BBStr *section,BBStr *key,bb_int_t value,bb_int_t update );
void BBCALL bbIniWriteFloat_( BBStr *path,BBStr *section,BBStr *key,bb_float_t value,bb_int_t update );
bb_int_t BBCALL bbIniSectionExist_( BBStr *path,BBStr *section,bb_int_t allow );
bb_int_t BBCALL bbIniKeyExist_( BBStr *path,BBStr *section,BBStr *key,bb_int_t allow );

// UE Reborn: S2IMap
bb_int_t BBCALL bbCreateS2IMap(  );
bb_int_t BBCALL bbS2IMapSize( bb_int_t map );
void BBCALL bbS2IMapErase( bb_int_t map,BBStr *key );
void BBCALL bbS2IMapSet( bb_int_t map,BBStr *key,bb_int_t value );
bb_int_t BBCALL bbS2IMapGet( bb_int_t map,BBStr *key );
bb_int_t BBCALL bbS2IMapContains( bb_int_t map,BBStr *key );
void BBCALL bbClearS2IMap( bb_int_t map );
void BBCALL bbDestroyS2IMap( bb_int_t map );

// UE Reborn: RapidBson
bb_int_t BBCALL bbJsonParseFromString( BBStr *json );
bb_int_t BBCALL bbJsonParseFromFile( BBStr *path );
bb_int_t BBCALL bbJsonHasParseError( bb_int_t document );
void BBCALL bbJsonFreeDocument( bb_int_t document );
bb_int_t BBCALL bbJsonGetValue( bb_int_t object,BBStr *name );
bb_int_t BBCALL bbJsonIsString( bb_int_t value );
bb_int_t BBCALL bbJsonIsFloat( bb_int_t value );
bb_int_t BBCALL bbJsonIsArray( bb_int_t value );
bb_int_t BBCALL bbJsonIsNull( bb_int_t value );
BBStr * BBCALL bbJsonGetString( bb_int_t value );
bb_int_t BBCALL bbJsonGetInt( bb_int_t value );
bb_float_t BBCALL bbJsonGetFloat( bb_int_t value );
bb_int_t BBCALL bbJsonGetBool( bb_int_t value );
bb_int_t BBCALL bbJsonGetArray( bb_int_t value );
bb_int_t BBCALL bbJsonGetArraySize( bb_int_t array );
bb_int_t BBCALL bbJsonGetArrayValue( bb_int_t array,bb_int_t index );

// UE Reborn: downloads, FreeImage, user32, uemp
BBStr * BBCALL bbFindNextDirectory( BBStr *path,BBStr *directory,BBStr *default );
void BBCALL bbDownloadFileThread( BBStr *url,BBStr *file );
bb_int_t BBCALL bbGetDownloadFileThreadSize(  );
bb_int_t BBCALL bbFI_Load( bb_int_t type,BBStr *file,bb_int_t mode );
bb_int_t BBCALL bbFI_Save( bb_int_t type,bb_int_t bitmap,BBStr *file,bb_int_t flags );
bb_int_t BBCALL bbFI_Unload( bb_int_t bitmap );
bb_int_t BBCALL bbFI_GetFIFFromFilename( BBStr *file );
bb_int_t BBCALL bbFI_Rescale( bb_int_t bitmap,bb_int_t width,bb_int_t height,bb_int_t filter );
bb_int_t BBCALL bbMemory_PeekInt( bb_int_t pointer );
void BBCALL bbMemory_PokeInt( bb_int_t pointer,bb_int_t value );
bb_int_t BBCALL bbapi_GetForegroundWindow(  );

#ifdef __cplusplus
}
#endif


#endif
