-- FMOD 3 (streams only; sound effects go through the Blitz audio commands)
FSOUND_Init%( freq%,channels%,flags% ):"bbFSOUND_Init"
FSOUND_Close%():"bbFSOUND_Close"
FSOUND_SetVolume( channel%,vol% ):"bbFSOUND_SetVolume"
FSOUND_SetVolumeAbsolute%( channel%,vol% ):"bbFSOUND_SetVolumeAbsolute"
FSOUND_GetVolume%( channel% ):"bbFSOUND_GetVolume"
FSOUND_SetPaused( channel%,paused% ):"bbFSOUND_SetPaused"
FSOUND_StopSound( channel% ):"bbFSOUND_StopSound"
FSOUND_Stream_Play%( channel%,stream% ):"bbFSOUND_Stream_Play"
FSOUND_Stream_Stop%( stream% ):"bbFSOUND_Stream_Stop"
FSOUND_Stream_Close%( stream% ):"bbFSOUND_Stream_Close"
FSOUND_Stream_Open%( filename$,mode%,memlength% ):"bbFSOUND_Stream_Open"
FSOUND_IsPlaying%( channel% ):"bbFSOUND_IsPlaying"
FSOUND_SetPan%( channel%,pan% ):"bbFSOUND_SetPan"

-- debug aid (not part of the original game)
RT_Trace( msg$ ):"bbRT_Trace"

-- on-screen keyboard (Switch); RT_HasPrompt% is 0 where a real keyboard exists
RT_HasPrompt%():"bbRT_HasPrompt"
RT_TextPrompt$( title$,initial$ ):"bbRT_TextPrompt"

-- port settings (switch_settings.ini, edited by the overlay menu)
RT_SettingF#( key$,def# ):"bbRT_SettingF"
RT_SettingI%( key$,def% ):"bbRT_SettingI"
RT_SettingS$( key$,def$ ):"bbRT_SettingS"

-- gamepad inventory navigation: the game reports the slot centres every frame an inventory is open
RT_PadInvBegin():"bbRT_PadInvBegin"
RT_PadInvSlot( x%,y% ):"bbRT_PadInvSlot"
RT_PadMenuBegin():"bbRT_PadMenuBegin"
RT_PadMenuRect( x%,y%,w%,h% ):"bbRT_PadMenuRect"

-- cpuid.dll
CPUid$():"bbCPUid"
CPUextendedId$():"bbCPUextendedId"
CPUbrand$():"bbCPUbrand"
CPUfeatures$():"bbCPUfeatures"
CPUmodel%():"bbCPUmodel"
CPUfamily%():"bbCPUfamily"
CPUsteppingId%():"bbCPUsteppingId"
CPUl1cache%():"bbCPUl1cache"
CPUl2cache%():"bbCPUl2cache"

-- BlitzMovie.dll (the startup video is not played)
BlitzMovie_Open%( name$ ):"bbBlitzMovie_Open"
BlitzMovie_Close():"bbBlitzMovie_Close"
BlitzMovie_GetWidth%():"bbBlitzMovie_GetWidth"
BlitzMovie_GetHeight%():"bbBlitzMovie_GetHeight"
BlitzMovie_GetPixel%( offset% ):"bbBlitzMovie_GetPixel"
BlitzMovie_Play%():"bbBlitzMovie_Play"
BlitzMovie_Stop%():"bbBlitzMovie_Stop"
BlitzMovie_OpenD3D%( name$,device%,ddraw% ):"bbBlitzMovie_OpenD3D"
BlitzMovie_DrawD3D%( x%,y%,width%,height% ):"bbBlitzMovie_DrawD3D"
BlitzMovie_MuteAudio%():"bbBlitzMovie_MuteAudio"
BlitzMovie_SetVolume%( volume% ):"bbBlitzMovie_SetVolume"
BlitzMovie_IsPlaying%():"bbBlitzMovie_IsPlaying"
BlitzMovie_OpenDecodeToImage%( name$,buffer%,looping% ):"bbBlitzMovie_OpenDecodeToImage"
BlitzMovie_OpenDecodeToTexture%( name$,buffer%,looping% ):"bbBlitzMovie_OpenDecodeToTexture"
BlitzMovie_Pause%():"bbBlitzMovie_Pause"

-- user32 / kernel32 (windowing is owned by the runtime)
api_GetClientRect%( hwnd%,rect% ):"bbapi_GetClientRect"
api_GetDesktopWindow%():"bbapi_GetDesktopWindow"
api_GetFocus%():"bbapi_GetFocus"
api_SetWindowLong%( hwnd%,index%,value% ):"bbapi_SetWindowLong"
api_SetWindowPos%( hwnd%,after%,x%,y%,cx%,cy%,flags% ):"bbapi_SetWindowPos"
api_GetModuleFileName%( module%,filename$,size% ):"bbapi_GetModuleFileName"
api_GlobalMemoryStatus( buffer* ):"bbapi_GlobalMemoryStatus"
GlobalMemoryStatus( buffer* ):"bbGlobalMemoryStatus"

-- zlibwapi.dll (only the self-updater uses it, and there is no updater here)
ZlibWapi_zError$( code% ):"bbZlibWapi_zError"
ZlibWapi_ZlibVersion$():"bbZlibWapi_ZlibVersion"
ZlibWapi_CompressBound%( length% ):"bbZlibWapi_CompressBound"
ZlibWapi_Compress%( dest%,destsize%,source%,sourcesize% ):"bbZlibWapi_Compress"
ZlibWapi_Compress2%( dest%,destsize%,source%,sourcesize%,level% ):"bbZlibWapi_Compress2"
ZlibWapi_UnCompress%( dest%,destsize%,source%,sourcesize% ):"bbZlibWapi_UnCompress"
ZlibWapi_Adler32%( adler%,buffer%,length% ):"bbZlibWapi_Adler32"
ZlibWapi_Crc32%( crc%,buffer%,length% ):"bbZlibWapi_Crc32"
ZlibWapi_UnzOpen%( path$ ):"bbZlibWapi_UnzOpen"
ZlibWapi_UnzClose%( zip% ):"bbZlibWapi_UnzClose"
ZlibWapi_UnzGetGlobalInfo%( zip%,info% ):"bbZlibWapi_UnzGetGlobalInfo"
ZlibWapi_UnzGetGlobalComment%( zip%,comment%,length% ):"bbZlibWapi_UnzGetGlobalComment"
ZlibWapi_UnzLocateFile%( zip%,name$,casesensitive% ):"bbZlibWapi_UnzLocateFile"
ZlibWapi_UnzGoToFirstFile%( zip% ):"bbZlibWapi_UnzGoToFirstFile"
ZlibWapi_UnzGoToNextFile%( zip% ):"bbZlibWapi_UnzGoToNextFile"
ZlibWapi_UnzGetCurrentFileInfo%( zip%,info%,name%,namesize%,extra%,extrasize%,comment%,commentsize% ):"bbZlibWapi_UnzGetCurrentFileInfo"
ZlibWapi_UnzOpenCurrentFile%( zip% ):"bbZlibWapi_UnzOpenCurrentFile"
ZlibWapi_UnzOpenCurrentFilePassword%( zip%,password$ ):"bbZlibWapi_UnzOpenCurrentFilePassword"
ZlibWapi_UnzReadCurrentFile%( zip%,buffer%,length% ):"bbZlibWapi_UnzReadCurrentFile"
ZlibWapi_UnzCloseCurrentFile%( zip% ):"bbZlibWapi_UnzCloseCurrentFile"
ZlibWapi_ZipOpen%( name$,append% ):"bbZlibWapi_ZipOpen"
ZlibWapi_ZipClose%( zip%,comment$ ):"bbZlibWapi_ZipClose"
ZlibWapi_ZipOpenNewFileInZip%( zip%,name$,info%,localextra%,localextrasize%,globalextra%,globalextrasize%,comment$,method%,level% ):"bbZlibWapi_ZipOpenNewFileInZip"
ZlibWapi_ZipOpenNewFileInZip3%( zip%,name$,info%,localextra%,localextrasize%,globalextra%,globalextrasize%,comment$,method%,level%,raw%,windowbits%,memlevel%,strategy%,password$,crc% ):"bbZlibWapi_ZipOpenNewFileInZip3"
ZlibWapi_ZipWriteFileInZip%( zip%,data%,length% ):"bbZlibWapi_ZipWriteFileInZip"
ZlibWapi_ZipCloseFileInZip%( zip% ):"bbZlibWapi_ZipCloseFileInZip"
